name = "inventory-backend"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
BACKEND_PORT = "3000"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "80a0ac7ff75441e9982b16cb4216a8df"

